### ISSUE TITLE
关于 OpenAI 接口请求超时

### ISSUE THREAD

**Issue by GanymedeNil** [GanymedeNil/document.ai#1]
长时间无法响应是因为OpenAI接口已经被ban，已经有很多公开的方案了，请善用搜索

**Comment by imchao9** [comment]
你好，我看了这个项目用的是httpx来进行的请求
而我通过httpx来请求，并设置代理后，访问向量服务器就会报502
目前没有找到比较好的解决办法，有什么思路可以提供一下吗

**Comment by GanymedeNil** [comment]
> 你好，我看了这个项目用的是httpx来进行的请求 而我通过httpx来请求，并设置代理后，访问向量服务器就会报502 目前没有找到比较好的解决办法，有什么思路可以提供一下吗

你可以尝试设置 no_proxy  向量服务器地址来绕过代理

**Comment by TOM08323049** [comment]
但是国内的IP被openai API拒绝访问，这个有什么办法解决吗？

**Comment by TOM08323049** [comment]
我在server.py的开头定义了这样，os.environ["http_proxy"] = "http://127.0.0.1:10010"
os.environ["https_proxy"] = "http://127.0.0.1:10010"
试图通过vpn来请求，但是出现这个报错：
    raise error.APIConnectionError(
openai.error.APIConnectionError: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/embeddings (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))
192.168.18.13 - - [16/Mar/2023 18:15:41] "POST /search HTTP/1.1" 500 -

**Comment by TOM08323049** [comment]
如果我根据自己的vpn设置端口，openai.proxy = 'http://127.0.0.1:10010'

**Comment by TOM08323049** [comment]
如果我根据自己的vpn设置端口，openai.proxy = 'http://127.0.0.1:10010/'
最后的报错是这样的qdrant_client.http.exceptions.ResponseHandlingException: timed out

**Comment by GanymedeNil** [comment]
> 如果我根据自己的vpn设置端口，openai.proxy = 'http://127.0.0.1:10010/' 最后的报错是这样的qdrant_client.http.exceptions.ResponseHandlingException: timed out

请查看上面我回复的
